# Generated by Django 4.1 on 2022-08-25 12:32

import courses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_user),
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_subject),
                related_name="courses",
                to="courses.subject",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=courses.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="file",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_user),
                related_name="%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=courses.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_user),
                related_name="%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_course),
                related_name="modules",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_user),
                related_name="%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(courses.models.get_sentinel_user),
                related_name="%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
