# Generated by Django 4.1 on 2022-09-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="courses.module",
            ),
        ),
    ]
