# Generated by Django 4.1 on 2022-09-05 22:06

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_content_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="url",
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
