name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Trigger everyday at 1 UTC
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

# Cancel any running workflow if the CI gets triggered again.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.2.2"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

      - name: Install the dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest --cov=./ --cov-report=xml

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2

  code-quality:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.2.2"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install the dependencies
        run: poetry install

      - name: Run black
        run: poetry run black . --check

      - name: Run isort
        run: poetry run isort . --check-only --profile black

      - name: Run flake8
        run: poetry run flake8 .
