name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2.2"]
        os: [ubuntu-latest]

    steps:
      - name: Deploy to server
        # don't run locally
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "Veer: running git pull..."
            git pull origin master

            echo "Veer: running poetry install..."
            /home/veer/.local/bin/poetry install

            # Veer try to refactor all these commands like
            # poetry run python ...
            # This way you don't have to specify the absolute path to python

            echo "Veer: collecting static..."
            /home/veer/.pyenv/versions/educa/bin/python manage.py collectstatic --noinput

            echo "Veer: showing migrations..."
            /home/veer/.pyenv/versions/educa/bin/python manage.py showmigrations

            echo "Veer: applying migrations..."
            /home/veer/.pyenv/versions/educa/bin/python manage.py migrate

            echo "Veer: running tests..."
            /home/veer/.pyenv/versions/educa/bin/python manage.py test -v 2

            echo "Veer: reloading daemon..."
            sudo systemctl daemon-reload

            echo "Veer: restarting gunicorn..."
            sudo systemctl restart gunicorn.service

            echo "Veer: restarting daphne..."
            sudo systemctl restart daphne.service

            echo "Veer: reloading nginx..."
            sudo nginx -s reload

            echo "Veer: All done! 💅💫💖"
